version: "2"
services:
  dongtai-mysql: 
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql:rw
  dongtai-redis:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:latest
    restart: always
  dongtai-webapi:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-webapi:latest
    restart: always
    volumes:
      - $PWD/config-tutorial.ini:/opt/dongtai/webapi/conf/config.ini

  dongtai-web:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-web:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dongtai-webapi

  dongtai-openapi:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-openapi:latest
    restart: always
    volumes:
       - $PWD/config-tutorial.ini:/opt/dongtai/openapi/conf/config.ini
    ports:
      - "8000:8000"

  dongtai-engine:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-engine:latest
    restart: always
    volumes:
      - $PWD/config-tutorial.ini:/opt/dongtai/engine/conf/config.ini


  dongtai-engine-task:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-engine:latest
    restart: always
    command: ["/opt/dongtai/engine/docker/entrypoint.sh", "task"]
    volumes:
      - $PWD/config-tutorial.ini:/opt/dongtai/engine/conf/config.ini
    depends_on:
      - dongtai-engine